name: goodman_pipeline
channels:
  - astroconda
dependencies:
  - numpy=1.15.2
  - pandas
  - matplotlib=3.0.1
  - scipy
  - cython
  - astropy>3
  - pip
  - pip:
    - ccdproc
    - coveralls
    - astroplan
    - sphinx
    - sphinxcontrib.napoleon
